### ISSUE TITLE
Digital twins architecture

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics#103]
In the technical architecture, IoT digital twins provide the visibility and monitoring of things and related events (e.g., using IoT devices to automatically capture the origin of a product), and blockchain enables the shared single version of the truth as to the state of these things across their life cycles and associated business events.

Robonomics Parachain provides an opportunity to create a model of a digital twin and update its state every 6 seconds, and important today describe the architecture of this.

**Comment by akru** [comment]
Probably, it could be fixed by adding documentation into https://github.com/airalab/robonomics/blob/master/robonomics/frame/digital-twin/src/lib.rs#L18

**Comment by akru** [comment]
Implemented in pallet-digital-twin
