### ISSUE TITLE
Robonomics IO read launch doesn't work as expected

### ISSUE THREAD

**Issue by tubleronchik** [airalab/robonomics#110]
# Problem
I tried to use robonomics io read launch but didn't get an expected result.

# Test
In one terminal i launched:
```
./robonomics io read launch --remote wss://mars.rpc.robonomics.network 
2021-01-27 13:59:01  Low open file descriptor limit configured for the process. Current value: 4096, recommended value: 10000.    
5Eg2fntNprdN3FgH4sfEaaZhYtddZQSQUqvYJ1f2mLtinVhV >> 5DhzHNWxgEs6i6TpMXF1TKcHAC4ifHDn2sdhMj9m4aUXgrjM : true
```
On [DAPP] (https://parachain.robonomics.network/?rpc=wss%3A%2F%2Fearth.rpc.robonomics.network#/extrinsics) i sent a launchXcm from Earth to Mars. 
In recent events i can see my launch with the correct address which doesn't match with the address from robonomics io.
![DAPP-launch](https://user-images.githubusercontent.com/36592446/105983869-64fde600-60aa-11eb-986b-99027c251d82.png)
# Expected results
I thought i should see the same address in the terminal as in DAPP.  I guess the problem can be with `ss58Format` in `spec.json` files. 
# Robonomics version 
```
./robonomics --version
robonomics 0.23.0-26529d07-x86_64-linux-gnu
 ```

**Comment by akru** [comment]
The default formatting is substrate, probably to change it we could introduce CLI parameter to set desired address codec

**Comment by akru** [comment]
Implemented
