### ISSUE TITLE
validator start error

### ISSUE THREAD

**Issue by lxgn** [airalab/robonomics#134]
Version: 0.27.0-ee4809f-x86_64-linux-gnu

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: start_thread
  31: clone

Thread 'tokio-runtime-worker' panicked at 'existence of block with number `new_canonical` implies existence of blocks with all numbers before it; qed', /home/runner/.cargo/git/checkouts/substrate-7e08433d4c370a21/401c24e/client/db/src/lib.rs:1183

This is a bug. Please report it at:

        https://github.com/airalab/robonomics/issues/new

**Comment by rk-p2p** [comment]
Same problem

**Comment by akru** [comment]
Hi, did you cleanup database before launch? If so, then please explain step-by-step how can I reproduce it.

**Comment by akru** [comment]
Please try latest release and reopen if still happes
