### ISSUE TITLE
Rws datalog

### ISSUE THREAD

**Issue by vol4tim** [airalab/robonomics#137]
Can't use rws datalog.

My steps.

1. Activated RWS token for address `4DjohM8jb4frM15ogKtAsyK1XfH6xgSYEpr7qPLcGna8oRrT`.

2. I sent an extrinsic.
![1](https://user-images.githubusercontent.com/14287968/114670871-80c17180-9d14-11eb-9f0a-f1f7068c4a57.png)

3. I see my events in the explorer.
![2](https://user-images.githubusercontent.com/14287968/114670924-9040ba80-9d14-11eb-92a9-50df2cdfbb9a.png)

4. I go to the block, but my extrinsic is not there .
https://parachain.robonomics.network/?rpc=wss%3A%2F%2Fearth.rpc.robonomics.network#/explorer/query/0x81106660e879341af219df2b80423e33cce470f2fc65e42bed36c14bf1788bd4

5. Datalog is empty too.
![3](https://user-images.githubusercontent.com/14287968/114671027-b0707980-9d14-11eb-9a0d-55e3c1f34b2b.png)

Chain RobonomicsEarth

**Comment by akru** [comment]
@vol4tim datalog() getter is deprecated, please use daralog_item()
