### ISSUE TITLE
building on m1 mac (missing: cumulus-pallet-xcm-handler)

### ISSUE THREAD

**Issue by bws9000** [airalab/robonomics#141]
command:
cargo install --force --git https://github.com/airalab/robonomics --tag v0.27.1 robonomics

result:
    Updating git repository `https://github.com/airalab/robonomics`
  Installing robonomics v0.27.0 (https://github.com/airalab/robonomics?tag=v0.27.1#ee4809f3)
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/cumulus`
    Updating git repository `https://github.com/paritytech/substrate`
    Updating git repository `https://github.com/paritytech/polkadot`
error: failed to compile `robonomics v0.27.0 (https://github.com/airalab/robonomics?tag=v0.27.1#ee4809f3)`, intermediate artifacts can be found at `/var/folders/qq/hwlm3q9s52zc9zcbmqwphnc40000gn/T/cargo-installcXA8yr`

Caused by:
  no matching package named `cumulus-pallet-xcm-handler` found
  location searched: https://github.com/paritytech/cumulus?branch=rococo-v1
  required by package `parachain-runtime v0.27.0 (/Users/burtsnyder/.cargo/git/checkouts/robonomics-17ef213c0350b51c/ee4809f/bin/node/runtime/parachain)`
      ... which is depended on by `node-cli v0.27.0 (/Users/burtsnyder/.cargo/git/checkouts/robonomics-17ef213c0350b51c/ee4809f/bin/node/cli)`
      ... which is depended on by `robonomics v0.27.0 (/Users/burtsnyder/.cargo/git/checkouts/robonomics-17ef213c0350b51c/ee4809f/bin/node)`

**Comment by akru** [comment]
Should be fixed in 0.28 release, please wait a bit or use 0.27 releases
