### ISSUE TITLE
Error while following the Kuka manipulator tutorial

### ISSUE THREAD

**Issue by nachikettapas** [airalab/robonomics#150]
I am following the Kuka manipulator tutorial on a fresh Ubuntu 18 VM (https://wiki.robonomics.network/docs/en/kuka/).
On step where you need to execute the following:
echo "ON" | ./robonomics io write launch -r <KUKA_ADDRESS> -s <WORK_KEY>

I get the following error:
Error: Input("The following types do not have a type size registered: ["RWS::Bandwidth::Perbill", "DigitalTwin::TopicChanged::H256", "Liability::NewReport::Report", "Liability::NewLiability::Economics", "Liability::NewLiability::Technics", "Datalog::NewRecord::Moment", "RWS::Subscription::T::AccountId", "Launch::NewLaunch::LaunchParameter", "Liability::NewReport::LiabilityIndex", "Liability::NewLiability::LiabilityIndex"] Use ClientBuilder::register_type_size to register missing type sizes.")

Environment:
Ubuntu 18
Robonomics v0.28.2 and v0.28.0

**Comment by akru** [comment]
Hi, it should be fixed in latest release, thank you
