### ISSUE TITLE
robonomics io write datalog error

### ISSUE THREAD

**Issue by tubleronchik** [airalab/robonomics#167]
# Problem
Hi
I am trying to use robonomics io write datalog, but haven't got an expected result.

# Test
In one terminal i launch:
```
echo "test" |  ./robonomics io write datalog -s <key>  --remote wss://ipci.rpc.robonomics.network
```
# Result
As the result i got such error:
```
thread 'main' panicked at 'there is no timer running, must be called from the context of a Tokio 0.2.x runtime', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/time/driver/handle.rs:24:32
```
I've tried to launch in local node as well:
```
./robonomics --dev  
echo "on" | ./robonomics io write datalog -s <KEY>
```
but got the same result.

# Robonomics version
```
./robonomics --version
robonomics 1.0.0-af3b009-x86_64-linux-gnu
```

**Comment by akru** [comment]
Thank you for the report @tubleronchik, looks like something wrong with the execution runtime for this command. It will be fixed in the next patch release.

**Comment by nakata5321** [comment]
Hello.

I see the same error, when run `robonomics io read launch` command.

# Test
First terminal:
```
 ./robonomics --dev --tmp 
```
then, in other terminal:
``` 
$ ./robonomics io read launch
```
# Result
```
thread 'async-std/runtime' panicked at 'there is no timer running, must be called from the context of a Tokio 0.2.x runtime', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/time/driver/handle.rs:24:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

robonomics version - robonomics 1.0.0-af3b009-x86_64-linux-gnu

**Comment by akru** [comment]
Should be fixed in https://github.com/airalab/robonomics/commit/99d70ca1baeccb19954c27fd29775d29f542497e
