### ISSUE TITLE
No documented alternative to the `robonomics io` command

### ISSUE THREAD

**Issue by arseniiarsenii** [airalab/robonomics#181]
Hello, I am trying to write string data into the datalog, however [instructions](https://wiki.robonomics.network/docs/en/rio-datalog/) provided in the wiki seem to be outdated.
```
$ echo "foo" | robonomics io write datalog -s 0xbdfe0930de2bb82...8e5634035d1997
error: Found argument 'io' which wasn't expected, or isn't valid in this context
```
I was not able to find an alternative way to write data into the datalog on the wiki. Is there any way to write arbitrary string or YAML data into the datalog as of today? Our project relies heavily on this functionality.

I am running latest version of Robonomics binary for Linux x86 under Ubuntu 20.04 LTS in a VM
```
$ robonomics -V
robonomics 1.1.0-3d61e8c-x86_64-linux-gnu
$ uname -a
Linux feecchub-VirtualBox 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by akru** [comment]
Hello, `robonomics io` isn't included in this release, it will be announced a bit later in one of patch releases.

**Comment by PaTara43** [comment]
Try this for strings 

https://github.com/PaTara43/robonomics_daos_toolkit/blob/main/common_utils.py
