### ISSUE TITLE
digitalTwin extrinsic is missing in 1.2

### ISSUE THREAD

**Issue by movefasta** [airalab/robonomics#189]
Following [Digital Twin example](https://wiki.robonomics.network/docs/en/digital-twins/) in Robonomics wiki i cannot find `digitalTwin` Extrinsic in `Menu -> Developer -> Extrinsics`.

network: main.frontier.rpc.robonomics.network
node: airalab-robonomics v1.2.0
account: 4DUoryWpsytkR8xFy58V98hjG9for1pArWHpE7UmbB5th6tZ
api v5.6.2-7
apps v0.95.2-50

**Comment by akru** [comment]
This pallet isn’t a part of main runtime, please use alpha or development version.
