### ISSUE TITLE
Robonomics exodus: a request to change the target address

### ISSUE THREAD

**Issue by Feedow** [airalab/robonomics#192]
{
  "address": "0xb5026494ea932cBd161c46392ffD7A2855Ca05Af",
  "msg": "Wrong target address: 4GbEH5acXaKeVv9DGAerD8qkFexHVotX7XYUcu98Uc2HQ21C. Right target address: 4FqBHafNHZuSg4Ufq2GPE6euYwWNqXrsLtv6qjNVANiB9bha",
  "sig": "0x624de926c09f28424e6a04792d0e8c98287a865e988e0c4c59306b964f70c3b43e06c3ccca1330108d2fecd94f28da8e2e7a6c9f453e2ec8a54b1e70113be1621b",
  "version": "2"
}

**Comment by dergudzon** [comment]
Hello, message signature verified: https://etherscan.io/verifySig/3416
Target address changed to 4FqBHafNHZuSg4Ufq2GPE6euYwWNqXrsLtv6qjNVANiB9bha
