### ISSUE TITLE
polkadot.js frontend does not working

### ISSUE THREAD

**Issue by mastercyb** [airalab/robonomics#210]
Go to https://parachain.robonomics.network and see no balances

<img width="1028" alt="xrt-not-working" src="https://user-images.githubusercontent.com/410789/139534366-efc83675-56ca-4a87-b1fe-ec9bd8bdac8e.png">

Than go to staking:

<img width="1280" alt="2021-10-30_16-10-52" src="https://user-images.githubusercontent.com/410789/139534202-d65abff8-b377-4e72-b6f2-7b9322d4908b.png">

On polkadot.js the same result

I bet endpoint is down

**Comment by dergudzon** [comment]
Hello! Try to use endpoint main.frontier.rpc.robonomics.network. Full link: https://parachain.robonomics.network/?rpc=wss%3A%2F%2Fmain.frontier.rpc.robonomics.network%2F#/accounts

Also you can switch to it in the menu:
![image](https://user-images.githubusercontent.com/6820574/139535843-f41dc688-a1cf-4ffb-b1e8-39f0c31cc03e.png)

**Comment by akru** [comment]
Hi @mastercyb, https://parachain.robonomics.network portal is for Robonomics Frontier parachain. Probably, you expect to see ERC20 balance here, unfortunately it's not the same as parachain native balance. You could be interested in one-way ERC20->Parachain transfer: https://dapp.robonomics.network/#/exodus

Unfortunately PolkadotApps portal doesn't support Robonomics Staking. Our Staking available on Robonomics DApp (detailed article https://robonomics.network/blog/xrt-staking-tech-committee-treasury-updates-1-2/): https://dapp.robonomics.network/#/staking/
