### ISSUE TITLE
Update and move "Building from source" and "Network maintaining" sections to wiki

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics#231]
We have Maintain section on wiki.

![Screenshot from 2022-01-08 19-05-23](https://user-images.githubusercontent.com/14291169/148649255-5785781b-2de1-432a-8ab7-2d7e3c38aef2.png)

New pages should be added asap:
How to build collator node.
Collator tip and tricks.

**Comment by dergudzon** [comment]
https://github.com/airalab/robonomics-wiki/pull/120

In progress

**Comment by dergudzon** [comment]
https://wiki.robonomics.network/docs/en/how-to-build-collator-node/
https://wiki.robonomics.network/docs/en/how-to-launch-the-robonomics-collator/
