### ISSUE TITLE
Docker Hub image is not updated

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics#232]
The releases page has a version issued 7 hours ago with a link to image at Docker Hub. But [Docker Hub page](https://hub.docker.com/r/robonomics/robonomics/tags) says the latest version available is published 6 months ago. Actions job related says it took more than 360 min for this job and the job was [canceled by timeout](https://github.com/airalab/robonomics/runs/4752550320?check_suite_focus=true#step:7:1413).

**Comment by khssnv** [comment]
Looks like a dedicated worker or a cache with cargo packages built may help.

**Comment by khssnv** [comment]
How to build your own image locally: https://khassanov.xyz/posts/launching-robonomics-collator-in-docker/.
Maybe it will help someone.

**Comment by akru** [comment]
Should be fixed now.
