### ISSUE TITLE
Parachain node stack with Err(Other(ClientImport("State Database error: Too many sibling blocks inserted"

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics#245]
After synchronizing with added state cache = 0, my raspberry pi 4 stack at block #175089. 
Console log: 

Feb 04 08:23:21 ubuntu robonomics[56033]: StateDatabase("Too many sibling blocks inserted")
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] 💔 Error importing block 0x6f89d3063e26e33f08ec9ba0c2d13bc178de829954f78c94e660b720d562d127: Err(Other(ClientImport("State Database error: Too many sibling blocks inserted")))
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] Block import error:
Feb 04 08:23:21 ubuntu robonomics[56033]: StateDatabase("Too many sibling blocks inserted")
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] 💔 Error importing block 0x6f89d3063e26e33f08ec9ba0c2d13bc178de829954f78c94e660b720d562d127: Err(Other(ClientImport("State Database error: Too many sibling blocks inserted")))

 
After service restart:

Feb 04 08:23:21 ubuntu robonomics[56033]: StateDatabase("Too many sibling blocks inserted")
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] 💔 Error importing block 0x6f89d3063e26e33f08ec9ba0c2d13bc178de829954f78c94e660b720d562d127: Err(Other(ClientImport("State Database error: Too many sibling blocks inserted")))
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] Block import error:
Feb 04 08:23:21 ubuntu robonomics[56033]: StateDatabase("Too many sibling blocks inserted")
Feb 04 08:23:21 ubuntu robonomics[56033]: 2022-02-04 08:23:21 [Parachain] 💔 Error importing block 0x6f89d3063e26e33f08ec9ba0c2d13bc178de829954f78c94e660b720d562d127: Err(Other(ClientImport("State Database error: Too many sibling blocks inserted")))

**Comment by akru** [comment]
Please use `--pruning archive` to escape this error.
