### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wwwAndries** [airalab/robonomics#283]
Ubuntu: 20.04 LTS
8 cores
30 GB RAM
robonomics 2.0.0-17b47a4bd7c

After upgrade to robonomics 2.0.0-17b47a4bd7c memory usage increases a lot! 
Just after restart node:
![image](https://user-images.githubusercontent.com/19406838/173180665-2727a22c-3265-490a-93d1-31201de70646.png)

After 45 min.
![image](https://user-images.githubusercontent.com/19406838/173181972-9d4ff3af-71af-4f41-a976-0b4aa378c85e.png)

After 2 h.
![image](https://user-images.githubusercontent.com/19406838/173185445-33a3c3e1-6929-435e-b3ff-0f7e3ed2d0b5.png)

![image](https://user-images.githubusercontent.com/19406838/173191407-50073bf0-905b-4f4f-8b70-1cf6f24d170f.png)

![image](https://user-images.githubusercontent.com/19406838/173194638-701b6f6b-efda-433b-be75-ffdfd4c46379.png)

Last 24 h:
![image](https://user-images.githubusercontent.com/19406838/173180490-d23f347c-8891-4294-b110-6f3deb96c0ec.png)

**Comment by wwwAndries** [comment]
I already did a rollback to 1.9.9, no memory issues with 1.9.9.

ExecStart=robonomics \
        --base-path ... \
        --parachain-id 2048 \
        --validator \
        --name 'StakeWorks | CVN0401 | Robonomics' \
        --lighthouse-account ... \
        --state-cache-size 1 \
        --prometheus-port 19655 \
        --telemetry-url="wss://telemetry.parachain.robonomics.network/submit/ 0" \
        --port 30353 \
        --ws-port 9954 \
        --rpc-port 9953 \
        -- \
        --database=RocksDb \
        --unsafe-pruning \
        --pruning=1000 \
        --port 30354 \
        --ws-port 9955 \
        --rpc-port 9956 \
        --no-prometheus

**Comment by akru** [comment]
Please checko v2.1.0 release, it should have patches that fix memory leak.

**Comment by akru** [comment]
Perfect, I close it then.
