### ISSUE TITLE
Invalid Transaction: Transaction has a bad signature

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics#314]
I'm unable to send a transaction from [https://polkadot.js.org/apps](https://polkadot.js.org/apps) interface. It prints `RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature` error message in the developer console. The most recent metadata installed. Please find the error message text and a full screenshot below.

### Versions
airalab-robonomics v2.4.0
api v9.8.2
apps v0.122.3-22

### Error

```console
WS endpoint= wss://kusama.rpc.robonomics.network/
web3Enable: Enabled 1 extension: polkadot-js/0.44.11
chain: Robonomics (Live), {"ss58Format":32,"tokenDecimals":[9],"tokenSymbol":["XRT"]}
web3Accounts: Found 5 addresses: ...
polkadot.02.43975fc1.js:1 2022-11-19 01:40:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
main.b24e5de3.js:2 signAndSend: error: d: 1010: Invalid Transaction: Transaction has a bad signature
polkadot.02.43975fc1.js:1 2022-11-19 01:40:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
```

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/833019/202789086-14c6d615-887f-4b08-86a5-af9bf347fa55.png)

</details>

**Comment by dergudzon** [comment]
This problem was related to a runtime update that added the crowdloan pallet.
Then the crowdloan pallet has been removed and transaction signatures are now working.
