### ISSUE TITLE
Error: Input when trying to export wasm runtime for mercury parachain

### ISSUE THREAD

**Issue by rafat** [airalab/robonomics#323]
I'm using robonomics v0.26.0 binary and I keep running into Error: Input when trying to export parachain wasm runtime and genesis state from mercury.raw.json chain spec file.

Here is the command I used

`./robonomics export-genesis-wasm --chain mercury.raw.json mercury-wasm` 

Here is the error.

`Error: Input("Error parsing spec file: expected value at line 9 column 1")`

**Comment by dergudzon** [comment]
Hello, are you sure you want to use version 0.26.0? It's very outdated at the moment.

The current version of Robonomics is 2.6.0: https://github.com/airalab/robonomics/releases/download/v2.6.0/robonomics-2.6.0-x86_64-unknown-linux-gnu.tar.gz

You can use the alpha-dev spec from v2.6.0. For example:
`./robonomics build-spec --chain alpha-dev > alpha-dev-spec.json`

**Comment by rafat** [comment]
Hi Thanks. I misstated the robonomics version. I am using the latest release - v2.6.0 and alpha-dev is working for me. This will do the job for us so I'm closing the issue.
