### ISSUE TITLE
Can`t build from source on Ubuntu 

### ISSUE THREAD

**Issue by EvgenRad81** [airalab/robonomics#43]
x86
Ubuntu 18.04.4 new installation.
Following the instructions - [Readme.adoc](https://github.com/airalab/robonomics/blob/master/README.adoc)

Get an error:
error: build of '/nix/store/8pwd7jfmg78szc8jmiv0lmp2xdb1qhvw-robonomics_msgs-master.drv', '/nix/store/alcz49g9lsdf8nwa4micx0ca74kz8kla-substrate_ros_msgs-master.drv', '/nix/store/myy9lwm90fv0rdy23ihr9b1gkfs0k93j-rust-1.42.0-nightly-2020-01-19-c0e02ad72.drv' failed

[log.txt](https://github.com/airalab/robonomics/files/4263299/log.txt)

**Comment by akru** [comment]
Hi @EvgenRad81, according to instruction: https://github.com/airalab/robonomics/blob/master/README.adoc#building-from-source
Nix isn’t required, please check steps and print it here when error raised again.

**Comment by EvgenRad81** [comment]
No luck.

evg@evg-NUC8i3BEH:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics --tag v0.15
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
error: failed to find tag `v0.15`

Caused by:
  reference 'refs/tags/v0.15' not found; class=Reference (4); code=NotFound (-3)

**Comment by akru** [comment]
Sure, because it’s not released yet, try to drop “—tag 0.15” key.

**Comment by akru** [comment]
I guess much more easy for you to use nightly builds from here: https://github.com/airalab/robonomics/actions/runs/45459647

**Comment by EvgenRad81** [comment]
> Sure, because it’s not released yet, try to drop “—tag 0.15” key.

evg@evg-NUC8i3BEH:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
error: multiple packages with binaries found: node-cli, subkey

**Comment by EvgenRad81** [comment]
> I guess much more easy for you to use nightly builds from here: https://github.com/airalab/robonomics/actions/runs/45459647

Thanks for that :) 
But I would like to be able to compile from source. The next step would be to launch robonomics on aarh64.

**Comment by akru** [comment]
Cargo install sentence from README  should works well now.

**Comment by EvgenRad81** [comment]
No luck :(

evg@evg-NUC8i3BEH:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
error: multiple packages with binaries found: node-cli, subkey
evg@evg-NUC8i3BEH:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics --tag v0.15
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
error: multiple packages with binaries found: node-cli, subkey

**Comment by akru** [comment]
Try to set concrete package using -p node-cli sentence

**Comment by EvgenRad81** [comment]
Looks like argument "-p" didn`t exist in cargo.

evg@DESKTOP-SMST3HV:~$ cargo install --force --git https://github.com/airalab/robonomics --tag v0.15 -p node-cli
error: Found argument '-p' which wasn't expected, or isn't valid in this context

USAGE:
    cargo install --force --git <URL> --tag <TAG>

For more information try --help

**Comment by akru** [comment]
Ok, try to remove “-p” from sentence

**Comment by EvgenRad81** [comment]
Starts well now. But crashes. Log in attachment.
[LOG030320.txt](https://github.com/airalab/robonomics/files/4281042/LOG030320.txt)

**Comment by akru** [comment]
Fixed at #45
