### ISSUE TITLE
[robonomics] sign data and broadcast

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics#46]
There is a scenario where we need to broadcast a valuable data over network signed by a private key

There were few cases where we didn't need a whole stack for example:

* https://github.com/Vourhey/sds011_sensor_agent
* https://github.com/Vourhey/libelium_sensor_collector
* https://github.com/Vourhey/uruguay_collector_server
* https://github.com/Vourhey/fuji_weather

In the examples above we didn't need a liability module (and blockchain part in particular) rather we needed IPFS part only

Launching let's say "signer only" would help to run our framework on low performance hardware like Raspberry Pi and similar ones

**Comment by akru** [comment]
What's about using `libp2p` [PeerId](https://docs.rs/libp2p/0.17.0/libp2p/struct.PeerId.html)  for each message? Every [GossipsubMessage](https://docs.rs/libp2p/0.17.0/libp2p/gossipsub/struct.GossipsubMessage.html) has it as `source` field.

PeerId could be derived by one of the following public keys:
* Ed25519
* RSA
* Secp256k1

https://docs.rs/libp2p/0.17.0/libp2p/identity/enum.PublicKey.html

**Comment by akru** [comment]
Implemented in [pubsub](https://github.com/airalab/robonomics/blob/master/robonomics/protocol/src/pubsub.rs#L33) module, each message has sender ID that could be used in pair with the static link to ETH/Polkadot/etc. account.
