### ISSUE TITLE
IPCI node: leak memory

### ISSUE THREAD

**Issue by illlefr4u** [airalab/robonomics#49]
The used memory of the validator node in the IPCI network is constantly growing, as can be seen in telemetry: https://telemetry.polkadot.io/#list/DAO%20IPCI 
My node is on version 0.17.0, and the memory consumed per day grew from 350 MB to 3 GB. Based on telemetry data, nodes on version 0.16.3 have a similar problem too.

Nodes has a memory leak. Kusama nodes had a similar problem on versions 0.7.20, which was fixed in version 0.7.21, so I assume that it is necessary to use a newer version of the substrate framework.

**Comment by akru** [comment]
@PavelSheremetev Could you share here Prometheus metrics of currently launched nodes. It could help to analyze memory leaks if it still happens.

@illlefr4u I recommend you to update up to `v0.17.2` release and keep in touch.

**Comment by akru** [comment]
As I can see this isn't looks actual for `v0.17.2`, @illlefr4u please feel free to reopen it when needed.
