### ISSUE TITLE
[Aira package] sds011 meet robonomics 2.0 datalog

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics#53]

**Comment by akru** [comment]
@ensrationis Could you provide some description, it's absolutely unclear from the issue name.

**Comment by ensrationis** [comment]
With @Vourhey we decided to make first movement for Aira on the way to use robonomics 2.0. We will try to use exist ROS topics in Aira to prepare rosbag and publish to ipfs. When Aira will get ipfs hash of rosbag data, she will send extrinsic to datalog function in robonomics 2.0 implementation.

**Comment by akru** [comment]
@ensrationis whats about to put above into issue description with separation of motivation, task, and desired behavior. It's a bit unclear why it's impossible to use ROS as a virtual device of the Robonomics I/O subsystem and makes robonomics io pipeline for this task.

For example:

```
rio read ros /some/ros/topic | rio write rosbag | rio write ipfs | rio write datalog
```

**Comment by ensrationis** [comment]
i'm agree with you @akru , after @Vourhey will teach Aira first time meet robonomics 2.0 we will shift to more detailed pipe with separation of motivation, task, and desired behavior. This issue just a scratch task to try, not more...

**Comment by Vourhey** [comment]
I prepared a small demo for the case. You can find the video [QmPqPw5Hoy222yWsStZ9CD96ffhEe9CXEAAv3cLE1npQAn](https://gateway.ipfs.io/ipfs/QmPqPw5Hoy222yWsStZ9CD96ffhEe9CXEAAv3cLE1npQAn).

To reproduce you'll need to clone this repository https://github.com/Vourhey/sds011_sensor_agent and follow the usual to launch the package except one thin. Additionally you'll need to have `robonomics` binary from [here](https://github.com/airalab/robonomics/releases) and a private key from your substrate account

I'll be glad to get any comments. It'd be helpful if @ensrationis and @PavelSheremetev try to launch the demo
