### ISSUE TITLE
v0.18.2 code build error in ubuntu 18.04

### ISSUE THREAD

**Issue by MinfonTsai** [airalab/robonomics#59]
execute: cargo install --force --git https://github.com/airalab/robonomics --tag v0.18.2 node-cli
and get error :
Compiling pallet-staking v2.0.0-rc4
   Compiling pallet-im-online v2.0.0-rc4
   Compiling pallet-babe v2.0.0-rc4
   Compiling pallet-grandpa v2.0.0-rc4
   Compiling pallet-authority-discovery v2.0.0-rc4
   Compiling substrate-subxt v0.8.0
error[E0107]: wrong number of type arguments: expected 0, found 1
  --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/substrate-subxt-0.8.0/src/rpc.rs:90:47
   |
90 | pub struct BlockNumber<T: System>(NumberOrHex<<T as System>::BlockNumber>);
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

error[E0107]: wrong number of type arguments: expected 0, found 1
  --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/substrate-subxt-0.8.0/src/rpc.rs:92:26
   |
92 | impl<T> From<NumberOrHex<<T as System>::BlockNumber>> for BlockNumber<T>
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

error[E0107]: wrong number of type arguments: expected 0, found 1
  --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/substrate-subxt-0.8.0/src/rpc.rs:96:28
   |
96 |     fn from(x: NumberOrHex<<T as System>::BlockNumber>) -> Self {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0107`.
error: could not compile `substrate-subxt`.

**Comment by akru** [comment]
Hello, could you try

cargo install --locked --force --git https://github.com/airalab/robonomics --tag v0.18.2 node-cli
