### ISSUE TITLE
Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)

### ISSUE THREAD

**Issue by PavelSheremetev** [airalab/robonomics#60]
when the validators of the test network polkadot work, the following messages began to appear
<details>
  <summary>parachain-validator-01</summary>
Jul 15 11:51:36 parachain-validator-01 polkadot[883235]: 2020-07-15 11:51:36 ✨ Imported #29059 (0xba15…a031)
Jul 15 11:51:36 parachain-validator-01 polkadot[883235]: 2020-07-15 11:51:36 ✍️ Starting parachain attestation session (parent: 0xba15…a031) with active duty LocalDuty { validation: Parachain(Id(100)), index: 2 }
Jul 15 11:51:36 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:36 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:36 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:36 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:36 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:36 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:36 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:36 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883235]: 2020-07-15 11:51:37 💤 Idle (18 peers), best: #29059 (0xba15…a031), finalized #29056 (0xeed8…ab70), ⬇ 13.7kiB/s ⬆ 15.7kiB/s
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:37 parachain-validator-01 polkadot[883407]: 2020-07-15 11:51:37 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:51:39 parachain-validator-01 polkadot[883235]: 2020-07-15 11:51:39 ⚠️  Polling the network future took 2.714866645s

</details>
<details>
  <summary>parachain-validator-02</summary>
Jul 15 11:46:42 parachain-validator-02 polkadot[760255]: 2020-07-15 11:46:42 ✨ Imported #29010 (0x4f49…2f00)
Jul 15 11:46:42 parachain-validator-02 polkadot[760255]: 2020-07-15 11:46:42 ✍️ Starting parachain attestation session (parent: 0x4f49…2f00) with active duty LocalDuty { validation: Parachain(Id(100)), index: 1 }
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:42 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:42 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:43 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:43 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:43 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:43 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:43 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:43 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:43 parachain-validator-02 polkadot[780855]: 2020-07-15 11:46:43 panicked at 'Calculates storage root: IncompleteDatabase(0xfb53f85b73f52eb4cf936ff527ccb7c1ff760d0399dd11707ad3d9b64d9dbdf7)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/03205eb/runtime/src/validate_block/implementation.rs:237:10
Jul 15 11:46:43 parachain-validator-02 polkadot[760255]: 2020-07-15 11:46:43 ♻️  Reorg on #29010,0x4f49…2f00 to #29010,0xd01f…d73b, common ancestor #29009,0x48df…868f
</details>

**Comment by akru** [comment]
Fixed in latest release
