### ISSUE TITLE
v0.18.4 code build error in ubuntu 18.04 

### ISSUE THREAD

**Issue by sun1534** [airalab/robonomics#61]
cd ~/go/src/github.com/robonomics
wget https://github.com/airalab/robonomics/archive/v0.18.4-parachain.tar.gz
tar -zxvf v0.18.4-parachain.tar.gz
cd robonomics-0.18.4-parachain
cargo build --verbose

**error: linking with `cc` failed: exit code: 1**
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "

**error: aborting due to previous error
error: could not compile `polkadot-cli`.**
Caused by:
  process didn't exit successfully: `rustc --crate-name polkadot_cli --edition=2018 /root/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/c2ef1f8/cli/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --crate-type rlib --emit=dep-info,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="cli"' --cfg 'feature="db"' --cfg 'feature="default"' --cfg 'feature="frame-benchmarking-cli"' --cfg 'feature="sc-cli"' --cfg 'feature="sc-service"' --cfg 'feature="service"' --cfg 'feature="service-old"' --cfg 'feature="tokio"' --cfg 'feature="wasmtime"'

**Comment by akru** [comment]
Did you install dependencies listed here? 

sudo apt install cmake git clang libclang-dev libudev-dev

**Comment by sun1534** [comment]
> Did you install dependencies listed here?
> 
> sudo apt install cmake git clang libclang-dev libudev-dev

did, i  already install it  Follow the tutorial

**Comment by sun1534** [comment]
> Did you install dependencies listed here?
> 
> sudo apt install cmake git clang libclang-dev libudev-dev

 did, i already install it by Follow the tutorial
.........
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
git is already the newest version (1:2.17.1-1ubuntu0.7).
libudev-dev is already the newest version (237-3ubuntu10.41).
clang is already the newest version (1:6.0-41~exp5~ubuntu1).
libclang-dev is already the newest version (1:6.0-41~exp5~ubuntu1).

**Comment by akru** [comment]
Oh, really. Could you put a full build log somewhere, please.

**Comment by sun1534** [comment]
> Oh, really. Could you put a full build log somewhere, please.

https://github.com/sun1534/file/blob/master/error-logs

**Comment by akru** [comment]
```
collect2: fatal error: ld terminated with signal 9 [Killed]
```
It looks like your build machine have no enough RAM to link binary.

**Comment by sun1534** [comment]
> ```
> collect2: fatal error: ld terminated with signal 9 [Killed]
> ```
> 
> It looks like your build machine have no enough RAM to link binary.

opps 。。tks,i will change a machine

**Comment by sun1534** [comment]
> > ```
> > collect2: fatal error: ld terminated with signal 9 [Killed]
> > ```
> > 
> > 
> > It looks like your build machine have no enough RAM to link binary.
> 
> opps 。。tks,i will change a machine

work, 2 CPUs, 8 GB memory.
