### ISSUE TITLE
Prometheus metrics for relaychain AND parachain

### ISSUE THREAD

**Issue by rk-p2p** [airalab/robonomics#63]
Сейчас в метриках прометея показывает данные только для parachain, а хотелось бы видеть данные и для relaychain.
Как пример, высота блоков:

```
...
# HELP substrate_block_height Block height info of the chain
# TYPE substrate_block_height gauge
substrate_block_height{status="best"} 11390
substrate_block_height{status="finalized"} 11390
substrate_block_height{status="sync_target"} 11390
...
```
```
...
Jul 21 15:31:24 robonomics-parachain-node01 robonomics[8194]: 2020-07-21 15:31:24 💤 [Parachain] Idle (25 peers), best: #11390 (0xf8cd…fb61), finalized #11390 (0xf8cd…fb61), ⬇ 2.1kiB/s ⬆ 1.8kiB/s
...
```

**Comment by akru** [comment]
@rk-p2p согласен, это было бы осень удобно.

Задача решается разработчиками cumulus, можно отслеживать здесь: https://github.com/paritytech/cumulus/issues/149

Хотя там про телеметрию, можно ещё про Prometheus добавить.

**Comment by akru** [comment]
@PavelSheremetev could you check it?

**Comment by PavelSheremetev** [comment]
для релей чейна так же есть метрики они поднимаются на отдельном порту:
`[Relaychain] 〽️ Prometheus server started at 127.0.0.1:9616`
`[Parachain] 〽️ Prometheus server started at 0.0.0.0:9615`
