### ISSUE TITLE
💔 Called on_block_announce with a bad peer ID

### ISSUE THREAD

**Issue by CNazar** [airalab/robonomics#64]
ubuntu 18.04 LTS
cpu:8
40 GB
ssd 700 GB

I noticed frequent mistakes about the inconsistency of "peers", after restart service everything returned to normal. I am adding a log:
https://drive.google.com/file/d/1H8iJvi6JHetLHuvdfFQj7Ew_v5zA9MS-/view?usp=sharing

**Comment by akru** [comment]
@CNazar could you check it on latest release please

**Comment by CNazar** [comment]
agreed so far without errors a new release
