### ISSUE TITLE
Systemd config and NixOS service

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics#69]
This is enhancement proposal. While we are trying to keep the node uptime higher, but failures still here, it would be great to have `systemd` config with right restart policy and logging length. Also NixOS `service.robonomics_node`in [airapkgs](https://github.com/airalab/airapkgs) would be handy for NixOS users to use this config straightforward.

**Comment by akru** [comment]
@PavelSheremetev do you have some?

**Comment by PavelSheremetev** [comment]
In airapkgs, this functional has already been implemented by the module:
https://github.com/airalab/airapkgs/blob/nixos-unstable/nixos/modules/services/robonomics/substrate-node-robonomics.nix
