### ISSUE TITLE
the node does not accept new blocks

### ISSUE THREAD

**Issue by PavelSheremetev** [airalab/robonomics#71]
<details>
  <summary>validator-01</summary>
<pre>
Aug 20 11:29:01 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:01 💤 Idle (854 peers), best: #184489 (0xd39f…11f2), finalized #184486 (0x9504…a98a), ⬇ 126.9kiB/s ⬆ 189.5kiB/s
Aug 20 11:29:04 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:04 Failed to collate candidate: Right(Canceled)
Aug 20 11:29:04 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:04 Failed to collate candidate: Right(Canceled)
Aug 20 11:29:04 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:04 Failed to collate candidate: Right(Canceled)
Aug 20 11:29:04 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:04 Failed to collate candidate: Right(Canceled)
Aug 20 11:29:04 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:04 Failed to collate candidate: Right(Canceled)
Aug 20 11:29:06 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:06 ✨ Imported #184490 (0x8e2f…96b5)
Aug 20 11:29:06 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:06 ✍️ Starting parachain attestation session (parent: 0x8e2f…96b5) with active duty LocalDuty { validation: Parachain(Id(100)), index: 1 }
Aug 20 11:29:07 parachain-validator-01 polkadot[1059]: thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
Aug 20 11:29:07 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:07 💤 Idle (854 peers), best: #184490 (0x8e2f…96b5), finalized #184487 (0x356c…b51a), ⬇ 66.6kiB/s ⬆ 174.2kiB/s
Aug 20 11:29:12 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:12 💤 Idle (854 peers), best: #184490 (0x8e2f…96b5), finalized #184488 (0x7200…32f3), ⬇ 130.2kiB/s ⬆ 259.9kiB/s
Aug 20 11:29:12 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:12 ✨ Imported #184491 (0x3d5e…9bc9)
Aug 20 11:29:12 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:12 ✍️ Starting parachain attestation session (parent: 0x3d5e…9bc9) with active duty LocalDuty { validation: Relay, index: 1 }
Aug 20 11:29:17 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:17 💤 Idle (854 peers), best: #184491 (0x3d5e…9bc9), finalized #184489 (0xd39f…11f2), ⬇ 225.5kiB/s ⬆ 185.3kiB/s
Aug 20 11:29:18 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:18 ✨ Imported #184492 (0x841e…07cc)
Aug 20 11:29:18 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:18 ✍️ Starting parachain attestation session (parent: 0x841e…07cc) with active duty LocalDuty { validation: Relay, index: 1 }
Aug 20 11:29:22 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:22 💤 Idle (853 peers), best: #184492 (0x841e…07cc), finalized #184489 (0xd39f…11f2), ⬇ 75.1kiB/s ⬆ 181.2kiB/s
Aug 20 11:29:24 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:24 🙌 Starting consensus session on top of parent 0x841e952d3decc9c39419e68e2889ab3cfa3a605efe42d16976ed8a9a446807cc
Aug 20 11:29:24 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:24 🎁 Prepared block for proposing at 184493 [hash: 0x516717c9131da3294335359d84351736ee3d37d4123f620f30d354b1f7fdb255; parent_hash: 0x841e…07cc; extrinsics (3): [0x140a…1410, 0x42ba…7aff, 0xd7e1…aab4]]
Aug 20 11:29:24 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:24 🔖 Pre-sealed block for proposal at 184493. Hash now 0xf5adb36958d843d67a0645c4ebe4e9975efd3dcd854d3441ab7afa823b073605, previously 0x516717c9131da3294335359d84351736ee3d37d4123f620f30d354b1f7fdb255.
Aug 20 11:29:24 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:24 ✨ Imported #184493 (0xf5ad…3605)
Aug 20 11:29:24 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:24 ✍️ Starting parachain attestation session (parent: 0xf5ad…3605) with active duty LocalDuty { validation: Parachain(Id(100)), index: 1 }
Aug 20 11:29:27 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:27 💤 Idle (852 peers), best: #184493 (0xf5ad…3605), finalized #184491 (0x3d5e…9bc9), ⬇ 187.1kiB/s ⬆ 294.5kiB/s
Aug 20 11:29:30 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:30 🙌 Starting consensus session on top of parent 0xf5adb36958d843d67a0645c4ebe4e9975efd3dcd854d3441ab7afa823b073605
Aug 20 11:29:30 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:30 🎁 Prepared block for proposing at 184494 [hash: 0xf1b2cb3c06b9ae03c95da298d3b5d84e044903c2b58e1e0f710de8a257958b99; parent_hash: 0xf5ad…3605; extrinsics (3): [0xf62a…cd44, 0x39bd…67e5, 0xd7e1…aab4]]
Aug 20 11:29:30 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:30 🔖 Pre-sealed block for proposal at 184494. Hash now 0x8196fd92dd696425722f63bc059526c32b155e808d72b3dbcbaee6d0fb056d22, previously 0xf1b2cb3c06b9ae03c95da298d3b5d84e044903c2b58e1e0f710de8a257958b99.
Aug 20 11:29:30 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:30 ✨ Imported #184494 (0x8196…6d22)
Aug 20 11:29:30 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:30 ✍️ Starting parachain attestation session (parent: 0x8196…6d22) with active duty LocalDuty { validation: Relay, index: 1 }
Aug 20 11:29:31 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:31 🔍 Discovered new external address for our node: /ip6/2a03:b0c0:0:1010::93:3001/tcp/30333/p2p/12D3KooWMdn7TpxN7mnk63sg3N8JxNpQiYDhWsjDFqheeJVEo8Do
Aug 20 11:29:31 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:31 ♻️  Reorg on #184494,0x8196…6d22 to #184494,0x5bd2…0e52, common ancestor #184493,0xf5ad…3605
Aug 20 11:29:31 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:31 ✨ Imported #184494 (0x5bd2…0e52)
Aug 20 11:29:31 parachain-validator-01 polkadot[706]: 2020-08-20 11:29:31 ✍️ Starting parachain attestation session (parent: 0x5bd2…0e52) with active duty LocalDuty { validation: Relay, index: 1 }
</pre>
</details>

<details>
  <summary>validator-02</summary> <pre>
Aug 20 11:33:36 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:36 ✨ Imported #184535 (0x3afa…5f1c)
Aug 20 11:33:36 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:36 ✍️ Starting parachain attestation session (parent: 0x3afa…5f1c) with active duty LocalDuty { validation: Parachain(Id(100)), index: 2 }
Aug 20 11:33:36 parachain-validator-02 polkadot[1188]: thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
Aug 20 11:33:36 parachain-validator-02 polkadot[1188]: thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
Aug 20 11:33:38 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:38 💤 Idle (849 peers), best: #184535 (0x3afa…5f1c), finalized #184532 (0x345b…91d2), ⬇ 141.3kiB/s ⬆ 341.0kiB/s
Aug 20 11:33:42 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:42 🙌 Starting consensus session on top of parent 0x3afa572600a1eea66cfc3e1f999a06ff1fca09f162085c63945b2e950abb5f1c
Aug 20 11:33:42 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:42 🎁 Prepared block for proposing at 184536 [hash: 0xc721d2669d1575176aa3d817b1ed0cf5819b12ae41be7108d39e867f898a85a4; parent_hash: 0x3afa…5f1c; extrinsics (3): [0x9231…e63d, 0xedb3…c73e, 0xd7e1…aab4]]
Aug 20 11:33:42 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:42 🔖 Pre-sealed block for proposal at 184536. Hash now 0xb01039afe218d8328266e665dd3938f49fc44844e61b4120938aa4a2cc9f3e8d, previously 0xc721d2669d1575176aa3d817b1ed0cf5819b12ae41be7108d39e867f898a85a4.
Aug 20 11:33:42 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:42 ✨ Imported #184536 (0xb010…3e8d)
Aug 20 11:33:42 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:42 ✍️ Starting parachain attestation session (parent: 0xb010…3e8d) with active duty LocalDuty { validation: Parachain(Id(100)), index: 2 }
Aug 20 11:33:42 parachain-validator-02 polkadot[1188]: thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
Aug 20 11:33:43 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:43 💤 Idle (849 peers), best: #184536 (0xb010…3e8d), finalized #184533 (0xfc88…652a), ⬇ 180.6kiB/s ⬆ 275.7kiB/s
Aug 20 11:33:44 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:44 🔍 Discovered new external address for our node: /ip6/2a03:b0c0:3:e0::4e4:2001/tcp/30333/p2p/12D3KooWA6bnssbSr8uabFyyuF2z2UFtFLp2Qwa6HWe7ohxFCBHx
Aug 20 11:33:48 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:48 ✨ Imported #184537 (0xfbdc…a819)
Aug 20 11:33:48 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:48 ✍️ Starting parachain attestation session (parent: 0xfbdc…a819) with active duty LocalDuty { validation: Parachain(Id(100)), index: 2 }
Aug 20 11:33:48 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:48 💤 Idle (849 peers), best: #184537 (0xfbdc…a819), finalized #184533 (0xfc88…652a), ⬇ 57.6kiB/s ⬆ 183.0kiB/s
Aug 20 11:33:53 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:53 💤 Idle (849 peers), best: #184537 (0xfbdc…a819), finalized #184535 (0x3afa…5f1c), ⬇ 149.0kiB/s ⬆ 284.3kiB/s
Aug 20 11:33:53 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:53 Failed to collate candidate: Right(Canceled)
Aug 20 11:33:53 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:53 Failed to collate candidate: Right(Canceled)
Aug 20 11:33:53 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:53 Failed to collate candidate: Right(Canceled)
Aug 20 11:33:53 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:53 Failed to collate candidate: Right(Canceled)
Aug 20 11:33:54 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:54 🙌 Starting consensus session on top of parent 0xfbdcbfa0c2bf87d07ae5da6f5037bbe9b94bbfa0ce7854633f9af0577044a819
Aug 20 11:33:54 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:54 🎁 Prepared block for proposing at 184538 [hash: 0x18c05a90acd28ad67c207d817ac9955e86ed4a0cf6343b18dda3f29af6fd5b3e; parent_hash: 0xfbdc…a819; extrinsics (3): [0xae22…f2d0, 0x1d32…17cf, 0xd7e1…aab4]]
Aug 20 11:33:54 parachain-validator-02 polkadot[707]: 2020-08-20 11:33:54 🔖 Pre-sealed block for proposal at 184538. Hash now 0x86e12c1bae8e297ec9483c9040d8af309bccffa6e424f0ebded33910cdbd53c3, previously 0x18c05a90acd28ad67c207d817ac9955e86ed4a0cf6343b18dda3f29af6fd5b3e.
</pre>
</details>

<details>
  <summary>collator-01</summary> <pre>
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 ♻️  [Relaychain] Reorg on #184563,0x9f15…8152 to #184563,0xd4ee…74bb, common ancestor #184562,0x4ae5…6967
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 ✨ [Relaychain] Imported #184563 (0xd4ee…74bb)
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 🙌 Starting consensus session on top of parent 0x8cbbcfbff396dfcec5b84ae4ac4188d1de7ef44558c2da71e14c1e39c814ebd1
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 Timeout fired waiting for transaction pool at block #100799. Proceeding with production.
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 🎁 Prepared block for proposing at 100800 [hash: 0x63fba635d34d2530a9589b67585e58ba5cc4cbfc3f8f41928cd8ae30135f7e40; parent_hash: 0x8cbb…ebd1; extrinsics (3): [0xea5a…4543, 0x7e18…6c41, 0x84fb…b4ca]]
Aug 20 11:36:25 rpc robonomics_run[24443]: 2020-08-20 11:36:25 ✨ [Parachain] Imported #100800 (0x63fb…7e40)
Aug 20 11:36:27 rpc robonomics_run[24443]: 2020-08-20 11:36:27 💤 [Parachain] Idle (225 peers), best: #100799 (0x8cbb…ebd1), finalized #100799 (0x8cbb…ebd1), ⬇ 77.1kiB/s ⬆ 3.2MiB/s
Aug 20 11:36:28 rpc robonomics_run[24443]: 2020-08-20 11:36:28 💤 [Relaychain] Idle (46 peers), best: #184563 (0xd4ee…74bb), finalized #184560 (0xd1ac…8079), ⬇ 13.4kiB/s ⬆ 15.9kiB/s
Aug 20 11:36:30 rpc robonomics_run[24443]: 2020-08-20 11:36:30 ✨ [Relaychain] Imported #184564 (0x9305…7056)
Aug 20 11:36:30 rpc robonomics_run[24443]: 2020-08-20 11:36:30 🙌 Starting consensus session on top of parent 0x8cbbcfbff396dfcec5b84ae4ac4188d1de7ef44558c2da71e14c1e39c814ebd1
Aug 20 11:36:30 rpc robonomics_run[24443]: 2020-08-20 11:36:30 Timeout fired waiting for transaction pool at block #100799. Proceeding with production.
Aug 20 11:36:30 rpc robonomics_run[24443]: 2020-08-20 11:36:30 🎁 Prepared block for proposing at 100800 [hash: 0x3f18c027a064f0d4a331ec1d3507bd2da81634a7a7f5901698570336e54b4ed0; parent_hash: 0x8cbb…ebd1; extrinsics (3): [0xa093…5276, 0xc36f…8f53, 0x84fb…b4ca]]
Aug 20 11:36:30 rpc robonomics_run[24443]: 2020-08-20 11:36:30 ✨ [Parachain] Imported #100800 (0x3f18…4ed0)
Aug 20 11:36:31 rpc robonomics_run[24443]: 2020-08-20 11:36:31 ♻️  [Relaychain] Reorg on #184564,0x9305…7056 to #184564,0x0547…48f0, common ancestor #184563,0xd4ee…74bb
</pre>
</details>

**Comment by akru** [comment]
Outdated
