### ISSUE TITLE
Robonomics IO read launch panics when idle 

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics#75]
Performing local tests with `robonomics --dev` network I noticed that `robonomics io read launch` crashes after some idle time

## How to reproduce 

One terminal window:
```
robonomics --dev --rpc-cors all
```

Another terminal window
```
robonomics io read launch
```

## Expected result

`rio read launch` is alive as long as `robonomics --dev` works

## Actual result

After some uncertain time

```
% ./robonomics io read launch
====================

Version: 0.21.0-31a135b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/option.rs:1273
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: async_task::raw::RawTask<F,R,S,T>::run
   8: multitask::Ticker::tick
   9: async_executor::Executor::run
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/sys/unix/thread.rs:87
  12: start_thread
  13: __clone


Thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Codec(Error("No such variant in enum Phase"))', robonomics/io/src/source/virt.rs:94

This is a bug. Please report it at:

        https://github.com/airalab/robonomics/issues/new
```

**Comment by KiichiSugihara** [comment]
I got the same bug on macOS, so I'll share it with you

```
❯ robonomics io read launch

====================

Version: 0.21.0-31a135b-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: _rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: async_task::raw::RawTask<F,R,S,T>::run
  10: multitask::Ticker::tick
  11: async_executor::Executor::run
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: __pthread_start


Thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Codec(Error("No such variant in enum Phase"))', robonomics/io/src/source/virt.rs:94

This is a bug. Please report it at:

	https://github.com/airalab/robonomics/issues/new

```

**Comment by PaTara43** [comment]
Got the same issue after making 2 transactions during 2 sequential blocks. After the 3rd block is calculated, bug appears

**Comment by akru** [comment]
@PaTara43 could you attach the error log here?

**Comment by PaTara43** [comment]
@akru, sure

`Version: 0.21.0-31a135b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/option.rs:1273
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: async_task::raw::RawTask<F,R,S,T>::run
   8: multitask::Ticker::tick
   9: async_executor::Executor::run
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/sys/unix/thread.rs:87
  12: start_thread
  13: __clone


Thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: TypeSizeUnavailable("Moment")', robonomics/io/src/source/virt.rs:94

This is a bug. Please report it at:

	https://github.com/airalab/robonomics/issues/new
`

**Comment by akru** [comment]
@PaTara43 thank you, looks like an undefined type than should be imported before sending transactions to the network. Is it happens on dev network?

**Comment by PaTara43** [comment]
@akru, yep, on `--dev`

**The full mise-en-scene:**

I launch the listener with 
```python
program = "<path_to_binary_file>/robonomics io read launch"
process = subprocess.Popen(program, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
listen to the network and do stuff if there is an "ON" transaction to a specific address:

```python
while True:
        output = process.stdout.readline()
        if output:
            if (">> " + <address> + " : true") in output.strip().decode('utf-8'):
                logging.warning('Transaction to start for ' + <address>)
                do_stuff_thread = Thread(target=do_stuff, args=(args,))
                do_stuff_thread.start()
            elif ('>> ' + <address> + " : false") in output.strip().decode('utf-8'):
                logging.warning('Transaction to stop for ' + <address>)
                class_instance.stop_flag = True
```

Inside the thread I do stuff with an instance of a class while the `class_instance.stop_flag` is not set. When it is set, I stop doing stuff and try to send `class_instance.data_string` to datalog with

```python
program = "echo \"" + <class_instance.data_string> + "\" | " + <path_to_binary_file> + "/robonomics io write datalog -s " + <key>
process = subprocess.Popen(program, shell=True, stdout=subprocess.PIPE)
output = process.stdout.readline()
logging.warning("Published data to chain. Transaction hash is " + output.strip().decode('utf8'))
```
The code is obviously simplified, but the main pattern of how I do it with robonomics is decribed. When i send an `echo "ON" | ...` transaction, I launch the thread, when I send an `echo "OFF" | ...` transaction, I stop the thread and instantly try to put some data to the network. It works fine, but when the next block is calculated, the bug appears.

I tried to catch the bug with:
```python
bug_catcher = Thread(target=catch_bugs, args=(args,))
bug_catcher.start()

...

def catch_bugs(args):
    error = process.stderr.readline()
    if error:
        logging.warning("Error in listener occurred, rebooting listener")
        listener() #reboot listener, calling the function with the code written above
```

Since it relaunches immediately, it catches the bug for 8 more seconds, rebooting the listener again and again, then it's ready to listen normally.

The problem is, if I send some transaction within the block, at the end of which the listener crashes, I lose the transaction.

**Comment by PaTara43** [comment]
New error got. When listening to some remote test network, after some time:


Version: 0.21.0-eb82a27-aarch64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530:17
   2: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437:5
   3: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85:14
   4: core::option::expect_none_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1269:5
   5: robonomics_io::source::virt::launch::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: async_task::raw::RawTask<F,T,S>::run
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: async_io::driver::block_on
  12: async_global_executor::init_with_config::{{closure}}
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87:17
  16: start_thread


Thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Codec(Error("No such variant in enum Phase"))', robonomics/io/src/source/virt.rs:94

**Comment by PaTara43** [comment]
When listening simultaneously from 2 different devices, error throws at the same time on both of them

**Comment by PaTara43** [comment]
I've noticed that this error is thrown when GRANDPA algorithm is applied. Maybe listener can't handle GRANDPA messages?

**Comment by akru** [comment]
It probably not affected to GRANDPA but something happens in the event handler, we should check carefully `unwrap()` methods.

**Comment by akru** [comment]
Feel free to open when happens on latest release
