### ISSUE TITLE
Robonomics io read ss58 address format

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics#84]
### Problem
I've followed [this](https://wiki.robonomics.network/docs/robonomics-test-network-manual/) manual and set up a bunch of nodes to form a test network, it works fine, I can see validators doing their job. With a shh tunnel I have an access to the DApp on parachain.robonomics.network, all right here.
![Screenshot from 2020-10-28 22-39-26](https://user-images.githubusercontent.com/34866682/97487930-9ca3a780-196e-11eb-89f1-c872c1502ac9.png)
The addresses here start from digit '4'
![Screenshot from 2020-10-28 22-41-18](https://user-images.githubusercontent.com/34866682/97488102-d70d4480-196e-11eb-8a99-2df2af313a55.png)
But when I try to send a transaction and catch it by listener I get this:
![image](https://user-images.githubusercontent.com/34866682/97488675-982bbe80-196f-11eb-8cff-a20769530aa3.png)
As may be seen, I send a transaction to the `4....` address, but the listener catches it as a transaction to `5...` address. With this I can't handle the transaction.

May be it's an address format issue.

### Troubleshooting
I've tried to use a spec.json file as an argument for the listener:
```
./robonomics io --chain robonomics_test_network/uploads/spec.json read launch
```
The result is the same

**Comment by akru** [comment]
Hi, thank you for report, best way in my opinion is set address prefix(network option) as key parameter, for example -n robonomics should use Robonomics network address prefix.

**Comment by PaTara43** [comment]
If you mean this
`./subkey -n robonomics generate `, it didn’t work either

**Comment by akru** [comment]
I mean io command should be extended by -n key for default address formatting scheme.

**Comment by PaTara43** [comment]
If you mean this: `./robonomics io read launch -n robonomics`
>>>
```
error: Found argument '-n' which wasn't expected, or isn't valid in this context

USAGE:
    robonomics io read launch [OPTIONS]

For more information try --help

```

**Comment by PaTara43** [comment]
update:

I've spotted that if I start a network with a `--dev`, addresses in DApp are starting with `5...`
And with the manual they start with `4...`

**Comment by PaTara43** [comment]
So the `ss58format` field in the spec file from the instruction is responsible for the address format in DApp, The listener always shows the transactions with addresses starting from `5...`

**Comment by akru** [comment]
Of course it should be implemented :)
I just try to formalize requirements for new feature here.

**Comment by PaTara43** [comment]
would you kindly provide me with the file format for `--dev` networks? The one that starts with `5..`?

**Comment by akru** [comment]
Yes, all formats available in substrate sources: https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L444

**Comment by akru** [comment]
Already implemented
