### ISSUE TITLE
Robonomics binary for arm processors missing launch module

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics#86]
I tried to send some transaction via rio with robonomics binary for arm
```
ubuntu@ubuntu:~$ echo "ON" | ./robonomics io write launch -s  <secret> -r <address>
Error: Input("Metadata error: Module Launch not found")
```

Therefore:
```
ubuntu@ubuntu:~$ ./robonomics io write launch
error: The following required arguments were not provided:
    -r <ROBOT_ADDRESS>
    -s <SECRET_URI>

USAGE:
    robonomics io write launch --remote <REMOTE_URI> -r <ROBOT_ADDRESS> -s <SECRET_URI>

For more information try --help
```

Datalog works fine

**Comment by akru** [comment]
Hello @PaTara43, thank you for report!

It looks like used runtime module didn't have launch pallet. Which network is used for?

**Comment by PaTara43** [comment]
> Hello @PaTara43, thank you for report!
> 
> 
> 
> It looks like used runtime module didn't have launch pallet. Which network is used for?

This:

https://github.com/airalab/robonomics/releases/download/v0.21.0/robonomics-ubuntu-0.21.0-aarch64.tar.xz

**Comment by akru** [comment]
I mean the node is connected for? The parachain, DAO IPCI, or local testnet?

**Comment by PaTara43** [comment]
> I mean the node is connected for? The parachain, DAO IPCI, or local testnet?

Oh, sorry. Launched in --dev mode

**Comment by akru** [comment]
Got it, the `launch` module isn't enabled in `--dev` environment. It will be enabled in next release.

**Comment by akru** [comment]
https://github.com/airalab/robonomics/pull/87/commits/e47c39a693b0f9a5778b992d0c6595597e1f4e1b

**Comment by PaTara43** [comment]
But I did use this for sending transactions like ON/OFF on x86.. on --dev chain

**Comment by akru** [comment]
Probably different commit is used for this build, @Vourhey could you rebuild ARM build from https://github.com/airalab/robonomics/tree/31a135b2062fa31db6d9d8b905142efb3f561ded

**Comment by Vourhey** [comment]
> Probably different commit is used for this build, @Vourhey could you rebuild ARM build from https://github.com/airalab/robonomics/tree/31a135b2062fa31db6d9d8b905142efb3f561ded

https://gateway.pinata.cloud/ipfs/QmccRGzbno6jhVcvUkXbYkN1A6kEoUxUYdWmmWdQ2n76Gq

**Comment by PaTara43** [comment]
Works now with recompiled binary
