### ISSUE TITLE
Error reading large datalog

### ISSUE THREAD

**Issue by vol4tim** [airalab/robonomics#92]
I am getting an error when reading from the datalog using @polkadot/api.

```
API-WS: disconnected from wss://substrate.ipci.io: 1009:: Maximum message size exceeded.
```

Example, an error can be received when reading with the address `4EH7FibXwt1FaNcQL9gsiHVxrt5MhG2LVYcut9QxygffKAok` from `wss://substrate.ipci.io/`.

Is it possible to read not all data, a one record, for example, by index?
Can you suggest another option, how you can read big datalog.

**Comment by akru** [comment]
yes, I guess we should provide some method to access it without fetching all the data, for example, by chunks or by index.

**Comment by akru** [comment]
Fixed in latest datalog version
