### ISSUE TITLE
Polkadot JS dashboard TX returns error.

### ISSUE THREAD

**Issue by banatarski** [airalab/robonomics#96]
Whenever I try to payout rewards I get the following error:

`1002: Verification Error: Execution: Trap: Trap { kind: Unreachable }: RuntimeApi, Execution: Trap: Trap { kind: Unreachable }`

**Comment by akru** [comment]
Could you explain step by step how can I reproduce this error?

**Comment by banatarski** [comment]
Yes,

1: Navigate to https://parachain.robonomics.network/#/staking/payout
2: Submit **payout all** transactions.
3: Sign with password which returns the error: `1002: Verification Error: Execution: Trap: Trap { kind: Unreachable }: RuntimeApi, Execution: Trap: Trap { kind: Unreachable }`

Issue started since last night.

**Comment by akru** [comment]
I see, it's for the IPCI chain, right? Please use the original IPCI explorer at https://ui.ipci.io
The parachain.robonomics.network was updated and could be temporarily incompatible with the IPCI chain.

**Comment by banatarski** [comment]
Thanks Akru.

Yes, correct. Regarding the IPCI chain.
Got it, just tried https://ui.ipci.io and can confirm it works.

Thanks!
