### ISSUE TITLE
I can not run correctly robonomics for move_arm_client.py for KUKA manipulator

### ISSUE THREAD

**Issue by masoudir** [airalab/robonomics#99]
Waiting for payment

====================

Version: 0.21.0-31a135b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/option.rs:1273
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: async_task::raw::RawTask<F,R,S,T>::run
   8: multitask::Ticker::tick
   9: async_executor::Executor::run
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libstd/sys/unix/thread.rs:87
  12: start_thread
  13: __clone

Thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Codec(Error("No such variant in enum Phase"))', robonomics/io/src/source/virt.rs:94

This is a bug. Please report it at:

	https://github.com/airalab/robonomics/issues/new

**Comment by akru** [comment]
Hello! Thank you for report!

Could you describe step by step how to repeat this error, please.

**Comment by masoudir** [comment]
I have solved this error. I did not executed the command for removing robonomics database before running it. 
Thanks for your attention
